image: gradle:8.2-jdk11
stages:
  - package
  - build
  - docker

package:
  stage: package
  script:
    - make package
  artifacts:
    expire_in: 1hr
    paths:
      - /

build:
  image: openjdk:11.0.1-jre
  stage: build
  script:
    - make build
  artifacts:
    expire_in: 1hr
    paths:
      - /

build-docker:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
    CRYPTOGRAPHY_DONT_BUILD_RUST: 1
  services:
  - docker:dind
  stage: docker
  environment: staging
  cache:
    paths:
      - node_modules/
  dependencies:
    - install-dependencies
  script:
    - echo "Build docker 🐳"
    - docker build . -t=kotlin-my-project-console:gitlab-build-${CI_PIPELINE_IID}
  artifacts:
    expire_in: 1hr
    paths:
      - build