language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
services:
  - docker
git:
  depth: 3
script:
  - ./gradlew package
  - ./gradlew build
  - docker build . -t=kotlin-my-first-project-console:travis-build-$TRAVIS_BUILD_NUMBER
on:
  branch: develop 