apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-10-05T05:14:16Z"
  generation: 1
  labels:
    app: kotlin-my-first-project-console
  name: kotlin-my-first-project-console
  namespace: default
  resourceVersion: "1538"
  uid: e6fd1baf-b065-40eb-92d2-2ab84abbebf6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kotlin-my-first-project-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kotlin-my-first-project-console
    spec:
      containers:
      - image: caprilespe/kotlin-my-first-project-console:v1
        imagePullPolicy: IfNotPresent
        name: kotlin-my-first-project-console
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-10-05T05:14:16Z"
    lastUpdateTime: "2023-10-05T05:14:16Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-10-05T05:14:16Z"
    lastUpdateTime: "2023-10-05T05:14:16Z"
    message: ReplicaSet "kotlin-my-first-project-console-c7566dd7f" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
